chore(commit): update commit

diff --git a/commit b/commit
--- a/commit
+++ b/commit
@@ -53,21 +53,28 @@ success() {
     echo -e "${Bold_Breen}$@ ${Color_Off}"
 }
 
-bold_success 
+# check is curl installed or not
+if ! command -v curl &> /dev/null
+then
+    error "commit uses curl for downloading files, please install curl and try again"
+fi
+
+bold_success
 bold_success █▀▀ █▀█ █▀▄▀█ █▀▄▀█ █ ▀█▀
 bold_success █▄▄ █▄█ █░▀░█ █░▀░█ █ ░█░
-bold_success 
+bold_success
 
-echo 
 echo -e "${Yellow}Commit${Color_Off} helps in better git experience and maintain proper commit messages."
 info "Commit uses gum for styling prompts."
-echo 
+echo
+info "Installing..."
 
 GUM_INSTALL_SETTING=$(echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list)
-GUM_INSTALL_LOG=$(sudo apt-get install gum)
+UPDATE_LOG=$(sudo apt-get update)
+GUM_INSTALL_LOG=$(sudo apt-get -y install gum)
 GUM_VERSION=$(gum -v)
 
-gum spin --spinner dot --title "Downloading gum..." --spinner.foreground="80" -- sleep 5 && echo -e "$GUM_VERSION downloaded. ${Cyan}https://github.com/charmbracelet/gum${Color_Off}"
+gum spin --spinner dot --title "Downloading gum..." --spinner.foreground="80" -- sleep 5 && echo -e "$GUM_VERSION downloaded. ${Cyan}https://github.com/charmbracelet/gum${Color_Off}" 
 
 commit_uri=https://raw.githubusercontent.com/KunalSin9h/commit/master/commit
 
@@ -84,11 +91,11 @@ if [[ ! -d $bin_dir ]]; then
 fi
 
 curl -fsSL --fail --location --output "$sh" "$commit_uri" ||
-    echo -e  "${Red}Failed${Color_Off} to download commit from ${Cyan}\"$commit_uri\"${Color_Off}"
+  error "Failed to download commit from \"$commit_uri\""
 
-gum spin --spinner dot --title "Downloading commit..." --spinner.foreground="80" -- sleep 5  && echo -e "commit version v0.0.1 (c1aa0a6) downloaded. ${Cyan}https://github.com/KunalSin9h/commit${Color_Off}"
+gum spin --spinner dot --title "Downloading commit..." --spinner.foreground="80" -- sleep 5  && echo -e "commit version v0.0.1 (.) downloaded. ${Cyan}https://github.com/KunalSin9h/commit${Color_Off}"
 
-gum spin --spinner dot --title "Setting Up..." --spinner.foreground="80" -- sleep 3 
+gum spin --spinner dot --title "Setting Up..." --spinner.foreground="80" -- sleep 3
 
 chmod +x "$sh" ||
     error 'Failed to set permissions on commit executable'
@@ -103,7 +110,7 @@ tildify() {
     fi
 }
 
-echo 
+echo
 success "commit was installed successfully to $Bold_Green$(tildify "$sh")"
 
 refresh_command=''
@@ -178,7 +185,7 @@ zsh)
     fi
     ;;
 *)
-    echo 'Manually add the directory to ~/.bashrc (or similar):'
+    echo -e "Manually add the directory to ${Yellow}~/.bashrc${Color_Off} (or similar):"
     info_bold "  export $install_env=$quoted_install_dir"
     info_bold "  export PATH=\"$bin_env:\$PATH\""
     ;;
@@ -191,4 +198,3 @@ echo
 if [[ $refresh_command ]]; then
     info_bold " $refresh_command"
 fi
-
